name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-181.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  protobuf: ^3.1.0
  shared_preferences: ^2.2.3
  flutter_background_service: ^5.0.1
  flutter_local_notifications: ^15.1.1
  flutter_background_service_android: ^6.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
