#!/bin/bash
evans --host localhost --port 9090 -r repl --header="Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiaXJvbm1hbiIsImlzc3VlZF9hdCI6IjIwMjQtMDUtMjRUMDI6Mjg6NDMuMTc3NTU2KzA5OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjQtMDUtMjRUMTI6Mjg6NDMuMTc3NTU2KzA5OjAwIn0.LvHBA7x58vq-NxFMPr-N-JDdmnZV1AuCk-rzz7ggZTg"
